<!DOCTYPE html>
<html>
    <?php
        include_once('template/head.php');
    ?>
    <body>
        <?php
            include_once('template/header.php');
        ?>
        <main>
            <?php
                include_once('src/core/router.php');
            ?>
        </main>
        <?php
            include_once('template/footer.php');
        ?>
    </body>
</html>